id: P79E93E43
initial_creation_type: input
source_metadata:
  title: Dzongter Kunzang Nyima
  language: en
  description: 'Texts by and about Dzongter Kunzang Nyima (rdzong gter kun bzang nyi
    ma, 1904–1958), the grandson and enlightened speech incarnation of Dudjom Lingpa
    (1835–1904):'
  volume:
    4f5ec752a4fd4d61b6a1d859c59c33a3:
      title: A Prayer to the Precious Guru from Uḍḍiyāna That Spontaneously Fulfils
        All Wishes
      parent: Guru Rinpoche Prayers
created_at: '2022-02-28T23:12:41.583586'
last_modified_at: '2022-02-28T23:12:41.583592'
